name: clean_arch_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.0
  get_it: ^7.6.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.15
  path: ^1.8.3
  path_provider: ^2.0.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  drift_dev: ^2.9.0
flutter:
  uses-material-design: true
  generate: true